" Standard vim options
set autoindent            " always set autoindenting on
set backspace=2           " allow backspacing over everything in insert mode
set cindent               " c code indenting
set diffopt=filler,iwhite " keep files synced and ignore whitespace
set expandtab             " Get rid of tabs altogether and replace with spaces
set foldlevel=0           " show contents of all folds
set foldmethod=indent     " use indent unless overridden
set guioptions-=m         " Remove menu from the gui
set guioptions-=T         " Remove toolbar
set hidden                " hide buffers instead of closing
set history=50            " keep 50 lines of command line history
set ignorecase            " Do case insensitive matching
set incsearch             " Incremental search
set laststatus=2          " always have status bar
set linebreak             " This displays long lines as wrapped at word boundries
set matchtime=10          " Time to flash the brack with showmatch
set nobackup              " Don't keep a backup file
set nocompatible          " Use Vim defaults (much better!)
set nofen                 " disable folds
set notimeout             " i like to be pokey
set ttimeout              " timeout on key-codes
set ttimeoutlen=100       " timeout on key-codes after 100ms
set ruler                 " the ruler on the bottom is useful
set scrolloff=1           " dont let the curser get too close to the edge
set shiftwidth=4          " Set indention level to be the same as softtabstop
set showcmd               " Show (partial) command in status line.
set showmatch             " Show matching brackets.

set textwidth=0           " Don't wrap words by default
set textwidth=80          " This wraps a line with a break when you reach 80 chars
set virtualedit=block     " let blocks be in virutal edit mode
set wildmenu              " This is used with wildmode(full) to cycle options
set relativenumber        " Relative line numbering
syntax enable
syntax on

" Turn off auto-splitting of long lines
set formatoptions-=tc

set nu
set tabstop=4
set shiftwidth=4
set relativenumber
set colorcolumn=80
set t_Co=256
set colorcolumn=81
highlight ColorColumn ctermbg=236
highlight StatusLine ctermbg=2 ctermfg=236

""" Functions

" Markdown heading
function M1()
	:normal yy
	:normal p
	:s/./=/g
    :normal o
    :normal o
	:startinsert!
endfunction

" Markdown subheading
function M2()
	:normal yy
	:normal p
	:s/./-/g
    :normal o
    :normal o
	:startinsert!
endfunction


map <leader>m1 :call M1()<CR>
map <leader>m2 :call M2()<CR>

" Map double-, to escape
imap ,, <Esc>




