# allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

# keep background processes at full speed
setopt NOBGNICE

# history
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# never ever beep ever
setopt NO_BEEP

# automatically decide when to page a list of completions
LISTMAX=0

# git tab completion
autoload -Uz compinit && compinit

# disable mail checking
MAILCHECK=0

# Colors
autoload -U colors
colors

# Aliases
alias ls='ls -lsHFG'

# Set Prompt
PS1=$'%F{cyan}%m%F{red} :: %F{cyan}%3(C#../#)%2d %F{red}$ %F{white}'

# No right-prompt
RPROMPT=''

# Ctrl-rightarrow and Ctrl-leftarrow to go forward/backward on command line
bindkey -e
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word

# Mac fix to get some Python-related VIM plugins to use brew-installed Python
# See: https://github.com/Valloric/YouCompleteMe/issues/620
unamestr=`uname`
if [[ "$unamestr" == 'Darwin' ]]; then
    export DYLD_FORCE_FLAT_NAMESPACE=1
fi

# Source local zshrc
if [[ -e ~/.zshrc_local ]]; then
    source ~/.zshrc_local
fi

