# allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

# keep background processes at full speed
setopt NOBGNICE

# history
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# never ever beep ever
setopt NO_BEEP

# automatically decide when to page a list of completions
LISTMAX=0

# disable mail checking
MAILCHECK=0

# Colors
autoload -U colors
colors

# Aliases
alias ls='ls -lsHFG'

# Set Prompt
PS1=$'%F{cyan}%m%F{red} :: %F{cyan}%3(C#../#)%2d %F{red}$ %F{white}'

# No right-prompt
RPROMPT=''

# Source local zshrc
if [[ -e .zshrc_local ]]; then
    source .zshrc_local
fi

